### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by fabaff** [alextaujenis/RBD_Button#1]
Installing RBD_Button with the Library Manager misses RBD_Timer.

```
/tmp/arduino_aa9a38b6f447ba36b966f131e49f13bb/push_button_disable_pullup.ino:6:23: fatal error: RBD_Timer.h: No such file or directory
 #include <RBD_Timer.h>
```

**Comment by alextaujenis** [comment]
At the moment the Arduino library manager can't install dependencies. I'll update the description to let people know they need to install the Timer as well.

[https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ](https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#when-i-install-a-library-that-i-know-depends-on-another-library-will-this-other-library-be-installed-as-well)

> When I install a library that I know depends on another library, will this other library be installed as well?
> 
> No, at the moment library dependencies are ignored. Current Library Manager aims at simplifying your life when dealing with installing a single library. If a library depends on another one, you'll have to install both.
