### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Bwanna** [alextaujenis/RBD_Button#8]
My sketch uses RBD in normal use of my sketch and it works great!  (Thanks!)

I'm planning on adding code to place it into Sleep Mode so only the INT0 or INT1 will wake it.  

Question:  Without resetting the Arduino through any of this, can I use attachInterrupt() just prior to sleeping and detachInterrupt() just after waking without a conflict occurring with the RBD assignment?

**Comment by alextaujenis** [comment]
This library stores an internal reference to the pin number and calls `digitalRead(_pin)` on each loop to report if the button is pressed or not. I don't think attaching or detaching interrupts would interfere with the pin binding.
